## data cleaning and preprocessing

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Airbnb_Open_Data.csv",low_memory=False) #license column contains different types of values,so we have to use low_mwemory=false.

In [4]:
#view the dataset
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [60]:
#check dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102058 entries, 0 to 102057
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102058 non-null  int64
 1   NAME                            101808 non-null  str
 2   host id                         102058 non-null  int64
 3   host_identity_verified          101769 non-null  str
 4   host name                       101654 non-null  str
 5   neighbourhood group             102029 non-null  str
 6   lat                             102050 non-null  float64
 7   long                            102050 non-null  float64
 8   country                         102058 non-null  str
 9   country code                    102058 non-null  str
 10  instant_bookable                102058 non-null  object
 11  cancellation_policy             101982 non-null  str
 12  room type                       102058 non-null  str
 13  Construction year               102058 non-null  float64
 14  price                           83999 non-null   float64
 15  service fee                     101785 non-null  float64
 16  minimum nights                  102058 non-null  float64
 17  number of reviews               101875 non-null  float64
 18  last review                     86226 non-null   datetime64[us]
 19  reviews per month               102058 non-null  float64
 20  review rate number              102058 non-null  float64
 21  calculated host listings count  102058 non-null  float64
 22  availability 365                102058 non-null  float64
 23  house_rules                     102058 non-null  str
 24  license                         2 non-null       str
dtypes: datetime64[us](1), float64(11), int64(2), object(1), str(10)
memory usage: 19.5+ MB

In [61]:
df.shape # column and rows

(102058, 25)

In [62]:
#remove extra spaces column name
df.columns=df.columns.str.strip()

In [63]:
#check missing values
df.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            404
neighbourhood group                   29
lat                                    8
long                                   8
country                                0
country code                           0
instant_bookable                       0
cancellation_policy                   76
room type                              0
Construction year                      0
price                              18059
service fee                          273
minimum nights                         0
number of reviews                    183
last review                        15832
reviews per month                      0
review rate number                     0
calculated host listings count         0
availability 365                       0
house_rules                            0
license                           102056
dtype: int64

In [10]:
df.describe() #showing statistical summary

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [64]:
#remove duplicates
df.duplicated().sum()

np.int64(0)

In [65]:
#remove duplicate records
df=df.drop_duplicates()

### handle missing values

In [66]:
# most missing values involves license column so drop it.
df.drop(columns=["license"],inplace=True)

In [67]:
df.drop(columns=["NAME"],inplace=True) #drop the name column

In [74]:
#check missing values
df['host_identity_verified'].isnull().sum()

np.int64(289)

In [75]:
df['host_identity_verified'].unique()

<StringArray>
['unconfirmed', 'verified', nan]
Length: 3, dtype: str

In [76]:
df['host_identity_verified']=df['host_identity_verified'].fillna(df['host_identity_verified'].mode()[0])

In [77]:
#verify 
df['host_identity_verified'].isnull().sum()

np.int64(0)

In [79]:
#check the missing value remains
df['host name'].isnull().sum()

np.int64(404)

In [80]:
df['host name']=df['host name'].fillna('Unknown')

In [81]:
#verify
df['host name'].isnull().sum()

np.int64(0)

In [68]:
#.filna= replace all NaN value with the value you provide 
#.mode()return the most frequent value in that columns,it returns the a series ,so [0] selects the the first mode 
df['neighbourhood group']=df['neighbourhood group'].fillna(df['neighbourhood group'].mode()[0])

In [69]:
df.drop(columns=["neighbourhood"],inplace=True)

KeyError: "['neighbourhood'] not found in axis"

In [70]:
#fill missing with mode
df['country']=df['country'].fillna('unknown')

In [13]:
df['country code']=df['country code'].fillna(df['country code'].mode()[0])

In [14]:
df['instant_bookable']=df['instant_bookable'].fillna(df['instant_bookable'].mode()[0])

In [15]:
df['room type']=df['room type'].fillna(df['room type'].mode()[0])

In [17]:
#fill missing with median
df['Construction year']=df['Construction year'].fillna(df['Construction year'].median())

In [55]:
df['price'].dtype # this columns contain string

In [56]:
df['price'].head(10)

0      $966
1      $142
2      $620
3      $368
4      $204
5      $577
6       $71
7    $1,060
8    $1,018
9      $291
Name: price, dtype: str

In [58]:
#convert into numeric
df['price']=pd.to_numeric(df['price'].replace(r'[\$]','',regex=True),errors='coerce')

In [59]:
df['price'].dtype

dtype('float64')

In [82]:
#fill the missing values
df['price']=df['price'].fillna(df['price'].median())

In [86]:
df['price'].isnull().sum()

np.int64(0)

In [22]:
#remove $ and convert the numeric using regex - r'[\$']->removes $ and ,
#errors='coerce' is the parameter of pd.to_numeric()
df['service fee'] = pd.to_numeric( df['service fee'].replace(r'[\$,]', '', regex=True),errors='coerce')

In [87]:
#fill the missing values
df['service fee']=df['service fee'].fillna(df['service fee'].median())

In [88]:
df['service fee'].isnull().sum()

np.int64(0)

In [23]:
df['minimum nights']=df['minimum nights'].fillna(df['minimum nights'].median())

In [24]:
#errors='coerce' is also parameter  of pd.to_datetime
df['last review']=pd.to_datetime(df['last review'],errors='coerce')

In [89]:
#fill the missing values
df['last review']=df['last review'].fillna(df['last review'].mode()[0])

In [90]:
df['last review'].isnull().sum()

np.int64(0)

In [26]:
df['reviews per month']=df['reviews per month'].fillna(df['reviews per month'].median())

In [28]:
df['review rate number']=df['review rate number'].fillna(df['review rate number'].median())

In [29]:
df['calculated host listings count']=df['calculated host listings count'].fillna(df['calculated host listings count'].median())

In [37]:
df['availability 365'].dtype # this columns contain object

dtype('O')

In [38]:
#check what values in the col
df['availability 365'].head(20)

0     286.0
1     228.0
2     352.0
3     322.0
4     289.0
5     374.0
6     224.0
7     219.0
8     180.0
9     375.0
10      1.0
11    163.0
12    258.0
13     47.0
14     68.0
15    100.0
16    197.0
17     96.0
18    325.0
19    345.0
Name: availability 365, dtype: object

In [40]:
#if the values are just numbers stored as string,run:
df['availability 365']=pd.to_numeric(df['availability 365'],errors='coerce')

In [42]:
df['availability 365']=df['availability 365'].fillna(df['availability 365'].median())

In [43]:
df['availability 365'].head(10)

0    286.0
1    228.0
2    352.0
3    322.0
4    289.0
5    374.0
6    224.0
7    219.0
8    180.0
9    375.0
Name: availability 365, dtype: float64

In [50]:
df['house_rules']=df['house_rules'].fillna('Not provided')

In [97]:
df.to_csv("Airbnb_Open_Data_cleaned.csv",index=False)